### PR TITLE
Use a seperate "smaller" struct to pass the bot to handlers

### PR DESCRIPTION
**Pull request by icewind1991**
This both remove the need for the `Option::take()` jugling with handler
and allows handlers to clone to bot handle so they can later send
messages in the background

### CODE REVIEW

**Comment by zwieberl** [comment]
Hi, thanks! Had a quick look at it. Would have been a bit easier if the reformatting would be in a different commit, though ;-) 
From a superficial glance this seems good, but I want to test it out as well. Hopefully I can manage in the next few days.

**Comment by zwieberl** [comment]
Ok, this works for me. Only one request, though: Could you also update the module-description in `src/lib.rs`, which is not mentioning ActiveBot yet?

**Comment by icewind1991** [comment]
extended the documentation a bit

**Comment by zwieberl** [comment]
Brilliant! Thanks you!

**Pull request merged**
